theme = "gruvbox"

[editor]
shell = ["zsh", "-c"]
rulers = [80]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

# Keymap

[keys.insert.j]
j = "normal_mode"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
V = ["goto_first_nonwhitespace", "extend_to_line_end"]

# Space mode

[keys.normal.space]
space = "command_mode"
F = "file_picker_in_current_buffer_directory"
W = ["move_prev_word_start", "move_next_word_end", "search_selection", "global_search"]

# File explorer hack
e = [":new", ":insert-output lf -print-selection", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":redraw"]

[keys.select.space]
space = "command_mode"
F = "file_picker_in_current_buffer_directory"
W = ["search_selection", "global_search"]
