// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var obj = {
  key: 123123
};

var reco = /* record */[/* key */333];

var tu = /* tuple */[
  1,
  "a",
  "b",
  "c",
  "d"
];

exports.obj = obj;
exports.reco = reco;
exports.tu = tu;
/* No side effect */
