require('general/settings')
require('general/mappings')

require('colorschemes/github')

require('plugins')
require('plugins/vifm')
require('plugins/sneak')
require('plugins/kommentary')
require('plugins/fzf')
require('plugins/compe')
require('plugins/Navigator')
require('plugins/autopairs')
require('plugins/lualine')
require('plugins/ale')
require('plugins/fugitive')
require('plugins/treesitter')
require('plugins/lsp')
require('plugins/indent-blankline')

